---
version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:390403857216:task-definition/springtask:1"
        LoadBalancerInfo:
          ContainerName: "springcontainer"
          ContainerPort: 8080
